name: "Deploy Sytesbook WPWedding"

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: "8.3"
    - name: Check PHP version
      run: php --version
    - uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding
        path: repos/sytesbook-wpwedding
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
    - uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding-installer
        path: repos/sytesbook-wpwedding-installer
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
    - uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytes-react
        path: repos/sytes-react
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
    - name: "Composer install: sytesbook-wpwedding"
      run: |
        cd /repos/sytesbook-wpwedding
        composer install
    - name: "NPM install: sytes/react"
      run: |
        cd /repos/sytes-react
        npm install
    - name: "NPM install and build: sytesbook-wpwedding/wp/wp-content/themes/sytesbook-wpwedding"
      run: |
        cd /repos/sytesbook-wpwedding/wp/wp-content/themes/sytesbook-wpwedding
        npm install
        npm run build
