name: "Deploy Sytesbook WPWedding"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.3"

    - name: Check PHP version
      run: php --version

    - name: "Checkout: sytesbook-wpwedding"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding
        path: repos/sytesbook-wpwedding
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "Checkout: sytesbook-wpwedding-installer"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding-installer
        path: repos/sytesbook-wpwedding-installer
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "Checkout: sytes-react"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytes-react
        path: repos/sytes-react
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "Composer install: sytesbook-wpwedding"
      working-directory: ./repos/sytesbook-wpwedding
      run: composer install

    - name: "NPM install: sytes-react"
      working-directory: ./repos/sytes-react
      run: npm install

    - name: "NPM install and build: sytesbook-wpwedding/src/wp-content/themes/sytesbook-wpwedding"
      working-directory: ./repos/sytesbook-wpwedding/src/wp-content/themes/sytesbook-wpwedding
      run: |
        npm install
        npm run build

    - name: Creating ZIP to be deployed
      run: |
        rm -r ./repos/sytesbook-wpwedding/wp/wp-content
        rm -r ./repos/sytesbook-wpwedding/src/wp-content/themes/sytesbook-wpwedding/node_modules
        rm ./repos/sytesbook-wpwedding/wp/wp-config.php
        mkdir ./deploy
        cd ./repos/sytesbook-wpwedding
        zip -r ../../deploy/deploy.zip src vendor wp

    - name: Deploy ZIP to the webserver
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: ${{ vars.DEPLOYMENT_FOLDER_ON_SERVER }}
