name: "Deploy Sytesbook WPWedding"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - staging
          - production
      tag:
        type: string
        description: The branch, tag or SHA to checkout. Falls back to default branch if not given.
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.3"

    - name: Check PHP version
      run: php --version

    - name: "Checkout: sytesbook-wpwedding-deploy"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding-deploy
        path: repos/sytesbook-wpwedding-deploy
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "Checkout: sytesbook-wpwedding"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding
        ref: ${{ inputs.tag }}
        path: repos/sytesbook-wpwedding
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "Checkout: sytesbook-wpwedding-installer"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding-installer
        path: repos/sytesbook-wpwedding-installer
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "Checkout: sytes-react"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytes-react
        path: repos/sytes-react
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "Composer install: sytesbook-wpwedding"
      working-directory: ./repos/sytesbook-wpwedding
      run: composer install

    - name: "NPM install: sytes-react"
      working-directory: ./repos/sytes-react
      run: npm install

    - name: "NPM install and build: sytesbook-wpwedding/src/wp-content/themes/sytesbook-wpwedding"
      working-directory: ./repos/sytesbook-wpwedding/src/wp-content/themes/sytesbook-wpwedding
      run: |
        npm install
        npm run build
    
    - name: "Create package"
      id: create_package
      run: |
        ./create-package.sh ${{ secrets.DOTENV_VAULT_KEY }}

    - name: Deploy package to the webserver
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./package/
        server-dir: "${{ vars.DEPLOYMENT_FOLDER_ON_SERVER }}/"

    - name: Deploy on-site installer scripts to the webserver
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./installer/
        server-dir: "${{ vars.DOMAIN_FOLDER_ON_SERVER }}/installer/"

    - name: Install
      working-directory: ./repos/sytesbook-wpwedding-deploy
      run: |
        ./install.sh ${{ vars.DOMAIN_NAME }} ${{ steps.create_package.outputs.package_id }} ${{ vars.DEPLOYMENT_FOLDER_ON_SERVER }} ${{ vars.DOMAIN_FOLDER_ON_SERVER }}
