name: "Test random string generation"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Generate random string
      id: random_test
      run: |
        random_string=$(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | tail -n +1 | head -c 32 | xargs)
        echo "$random_string"
        echo "deployment_id=$random_string" >> $GITHUB_OUTPUT 

    - name: Read generated random string
      run: |
        echo "Generated random string: ${{ steps.random_test.outputs.deployment_id }}"
