name: "Set model instance deletion time"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - staging
          - production
      model-collection:
        type: string
        description: The model collection of the model instance whose deletion time has to be set.
        required: true
      model-uid:
        type: string
        description: The UID of the model instance whose deletion time has to be set.
        required: true
      deletion-time:
        type: string
        description: The new deletion time in 'YYYY-MM-DD HH:mm:SS' format, or the 'now' string to delete immediately, or null to remove the current deletion time
        required: false
      operator-username:
        type: string
        description: The username of the operator who is setting the deletion time.
        required: true
      operator-application-password:
        type: string
        description: The application password created for the operator who is setting the deletion time.
        required: true

jobs:
  set-deletion-time:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Check versions
      run: |
        echo "NodeJS version: $(node --version)"
        echo "NPM version: $(npm --version)"

    - name: "Checkout: sytesbook-wpwedding-deploy"
      uses: actions/checkout@v4
      with:
        repository: dkuratowski/sytesbook-wpwedding-deploy
        path: repos/sytesbook-wpwedding-deploy
        token: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: "NPM install: sytesbook-wpwedding-deploy"
      working-directory: ./repos/sytesbook-wpwedding-deploy
      run: |
        npm install

    - name: Set model instance deletion time
      env:
        OPERATOR_USERNAME: ${{ inputs.operator-username }}
        OPERATOR_PASSWORD: ${{ inputs.operator-application-password }}
      run: |
        node ./repos/sytesbook-wpwedding-deploy/set-deletion-time.js ${{ inputs.model-collection }} ${{ inputs.model-uid }} ${{ inputs.deletion-time }}
